### PR TITLE
Bump version tags to 3.2.0

### PR DESCRIPTION
**Pull request by charmasaur**
There have been a lot of improvements since the last release, so I think it's time for another.

### CODE REVIEW

**Comment by zakv** [comment]
I agree

Looks to me like this PR bumps the version number in all of the required places since all the lines changed in #64 and #65 are updated here, so I think this is good to go.

**Review by zakv — APPROVED** [review]

**Comment by zakv** [comment]
Did you want to publish this to PyPI or should I? If I remember correctly the only necessary steps were to:

1. Bump the version numbers as done in this PR.
2. Ensure you've checked out the master branch in your local repo and pulled the most recent changes.
4. Run `python setup.py sdist` to make a source distribution.
5. Do a dry run publishing to TestPyPI by running ` twine upload --repository testpypi dist/*` in the project root directory.
    * Pip or conda install twine if not already installed.
6.  If the previous step goes well, then run `twine upload dist/*` to publish to real PyPI.
7. Add a new build version on readthedocs.

Also, I just noticed that there's no project description on [the PyPI page](https://pypi.org/project/M-LOOP/). Maybe now would be a good time to add a brief description there with a link to the readthedocs for more info? I'm not sure how to do that but I imagine it's not too hard.

**Comment by charmasaur** [comment]
Thanks for the steps! I might as well try to do it myself, and I'll let you know if I run into issues. I think the description should just be a matter of tweaking `setup.py`, I'll try something and send a PR.

**Comment by charmasaur** [comment]
@zakv would you be able to make me a maintainer of https://test.pypi.org/project/M-LOOP/? My test.pypi username is charmasaur.

**Comment by charmasaur** [comment]
Should be mostly done, I'm just waiting on access to readthedocs from Michael.

**Pull request merged**
