### PR TITLE
Fix a bunch of typos

### PR DESCRIPTION
**Pull request by charmasaur**
Thanks to @abenseny.

### CODE REVIEW

**Review by abenseny — APPROVED** [review]

**Comment by zakv** [comment]
Awesome! Thanks @abenseny for taking care of that; I'm particularly glad to see all of that trailing whitespace go.

This might generate some merge conflicts with the other PRs open at the moment but they should all be easy fixes.

**Comment by abenseny** [comment]
No worries. I thought I had just fixed the typos, I don't remember doing any linting but I might have accidentally ran black on `learners.py`.

**Comment by charmasaur** [comment]
Ah, the whitespace was me. git had a go at me about the trailing whitespace when I tried to apply the patch, so I fixed the offending file. I'll take the opportunity to fix it throughout before merging.

@zakv I'll also hold off on this until your changes are in. I'd much rather deal with the conflicts in this PR than inflict them on yours!

**Comment by zakv** [comment]
> I'll also hold off on this until your changes are in

Sounds good! Were you hoping to take another look at #84? If not I could just merge it now. The changes you suggested so far there have all been implemented.

**Comment by charmasaur** [comment]
> > I'll also hold off on this until your changes are in
> 
> Sounds good! Were you hoping to take another look at #84? If not I could just merge it now. The changes you suggested so far there have all been implemented.

I was just taking some time while washing dishes to think about inheritance, I've added a rambling comment to the PR but have no suggestions for changes. Fire away!

**Comment by zakv** [comment]
Ok #84 has been merged, which unfortunately did lead to some merge conflicts

**Comment by zakv** [comment]
>  I'll take the opportunity to fix it throughout before merging.

Actually I ended up thinking of a couple of things I wanted to work on this weekend. To avoid more conflicts down the line I'll merge this now and then one of us can do a separate repo-wide whitespace removal PR soon. Hope you don't mind!

**Pull request merged**
